# Generated by Django 5.2 on 2025-04-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(max_length=50, verbose_name="Телеграм chat-id"),
        ),
    ]
