# Generated by Django 5.2 on 2025-04-30 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(blank=True, max_length=255, null=True, verbose_name="Место выполнения")),
                (
                    "action_time",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Время выполнения"),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Приятная привычка")),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="Периодичность выполнения"
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True, verbose_name="Вознаграждение")),
                (
                    "lead_time",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Продолжительность выполнения"),
                ),
                (
                    "is_public",
                    models.BooleanField(blank=True, default=False, null=True, verbose_name="Публичная привычка"),
                ),
                (
                    "associated_habit",
                    models.ManyToManyField(
                        blank=True, null=True, to="habits.habit", verbose_name="Связанная привычка"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
