# Generated by Django 5.2 on 2025-04-30 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="associated_habit",
        ),
        migrations.AddField(
            model_name="habit",
            name="associated_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
