# Generated by Django 5.2 on 2025-04-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_remove_habit_associated_habit_habit_associated_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Время выполнения"),
        ),
    ]
