# Generated by Django 5.2 on 2025-05-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_action_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notice_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата последнего уведомления"),
        ),
    ]
